'use strict';
const $=id=>document.getElementById(id);let state={entries:[]},current=null,dirty=false;
const pending=e=>!['approved','retired'].includes(e.status);
function notice(text='',kind='success'){ $('message').textContent=text; $('message').className=kind; }
async function request(route,data){const response=await fetch('/api/'+route,{method:'POST',headers:{'Content-Type':'application/json','X-Review-Token':state.token},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw Error(result.error);return result;}
function filtered(){const q=$('search').value.toLocaleLowerCase();return state.entries.filter(e=>(($('status').value==='pending'&&pending(e))||$('status').value==='all'||$('status').value===e.status)&&($('screen').value==='all'||$('screen').value===e.source.screen)&&(!q||[e.key,e.fi,e.source.en,e.source.context].join(' ').toLocaleLowerCase().includes(q)));}
function list(){const items=filtered();$('list').replaceChildren();for(const e of items){const b=document.createElement('button');b.className=e.key===current?.key?'selected':'';const title=document.createElement('span');title.textContent=e.source.en;const meta=document.createElement('small');meta.textContent=`${e.source.screen} · ${e.status}`;b.append(title,meta);b.onclick=()=>{if(!dirty||confirm('Discard unsaved edits?'))show(e);};$('list').append(b);}$('summary').textContent=`${state.entries.filter(e=>e.status!=='retired').length} active entries · ${state.entries.filter(pending).length} awaiting review · ${state.entries.filter(e=>e.status==='approved').length} approved`+(state.lastScan?` · Last check ${new Date(state.lastScan.at).toLocaleString()}`:'');}
function preview(){if(!current)return;$('preview').textContent=$('finnish').value.replace(/\{([a-zA-Z][\w]*)\}/g,(all,k)=>String(current.source.examples?.[k]??`[${k}]`));}
function show(e){current=e;dirty=false;$('editor').hidden=!e;$('empty').hidden=!!e;if(!e){list();return;}$('heading').textContent=e.source.screen;$('badge').textContent=e.status;$('context').textContent=e.source.context;$('english').textContent=e.source.en;$('finnish').value=e.fi;$('saveState').textContent='Saved';$('key').textContent=e.key;$('revision').textContent=`Source revision ${e.revision}`;$('suggestion').hidden=!e.suggestion;$('useSuggestion').hidden=!e.suggestion;$('suggestion').textContent=e.suggestion?`New suggestion: ${e.suggestion.fi}`:'';$('history').replaceChildren();e.history.map((h,index)=>({h,index})).reverse().forEach(({h,index})=>{const row=document.createElement('div');row.className='history-item';row.textContent=`${new Date(h.at).toLocaleString()} · ${h.action}\nEnglish: ${h.source?.en||''}\nContext: ${h.source?.context||''}\nFinnish: ${h.fi||'(missing)'}`;if(h.fi){const restore=document.createElement('button');restore.textContent='Restore as draft';restore.onclick=()=>perform(()=>save('undo',{historyIndex:index}));row.append(document.createElement('br'),restore);}$('history').append(row);});for(const id of ['save','approve','regenerate','finnish'])$(id).disabled=e.status==='retired';preview();list();}
async function refresh(preferred=current?.key){const response=await fetch('/api/state');if(!response.ok)throw Error('Could not load review queue');state=await response.json();const selected=$('screen').value;const screens=[...new Set(state.entries.map(e=>e.source.screen))].sort();$('screen').replaceChildren(new Option('All screens','all'),...screens.map(s=>new Option(s,s)));$('screen').value=screens.includes(selected)?selected:'all';const visible=filtered();show(visible.some(e=>e.key===preferred)?state.entries.find(e=>e.key===preferred):visible[0]||null);}
async function perform(fn){try{notice();await fn();}catch(e){notice(e.message,'error');}}
async function save(action,extra={}){if(!current)return;const candidates=filtered();const index=candidates.findIndex(e=>e.key===current.key);const next=candidates[index+1]?.key||candidates[0]?.key;const result=await request('save',{key:current.key,fi:$('finnish').value,version:current.version,sourceRevision:current.revision,action,...extra});await refresh(action==='approve'?next:current.key);notice(result.warning||'Saved. The app receives this text with its next release.',result.warning?'warning':'success');}
$('finnish').oninput=()=>{dirty=true;$('saveState').textContent='Unsaved changes';preview();};
for(const id of ['search','screen','status'])$(id).oninput=list;
$('save').onclick=()=>perform(()=>save('draft'));$('approve').onclick=()=>perform(()=>save('approve'));
$('skip').onclick=()=>{if(dirty&&!confirm('Discard unsaved edits?'))return;const items=filtered();show(items[(items.findIndex(e=>e.key===current?.key)+1)%items.length]||null);};
$('useSuggestion').onclick=()=>{$('finnish').value=current.suggestion.fi;$('finnish').oninput();};
$('regenerate').onclick=()=>perform(async()=>{if(dirty)throw Error('Save your draft before requesting a suggestion.');$('regenerate').disabled=true;notice('Generating a Finnish suggestion…','warning');try{await request('generate',{key:current.key,version:current.version});await refresh();notice('Suggestion ready. Human edits are preserved.');}finally{$('regenerate').disabled=false;}});
$('check').onclick=()=>perform(async()=>{if(dirty)throw Error('Save your draft before checking.');$('check').disabled=true;notice('Checking source changes and missing drafts…','warning');try{const result=await request('check',{});await refresh();const message=result.warning||(result.issues.length?result.issues.join('\n'):'Check complete.');notice(message,result.warning||result.issues.length?'warning':'success');}finally{$('check').disabled=false;}});
$('export').onclick=()=>{const entries=state.entries.filter(e=>e.status!=='retired'&&e.fi).map(e=>({key:e.key,fi:e.fi,version:e.version,sourceRevision:e.revision}));const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([JSON.stringify({schemaVersion:1,entries},null,2)],{type:'application/json'}));link.download='gymtrack-finnish-review.json';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);};
$('import').onchange=()=>perform(async()=>{if(dirty)throw Error('Save your draft before importing.');const file=$('import').files[0];if(!file)return;const data=JSON.parse(await file.text());await request('import',data);await refresh();notice('Imported as drafts. Approvals remain an individual review decision.');$('import').value='';});
$('exercises').onchange=()=>perform(async()=>{if(dirty)throw Error('Save your draft before importing.');const file=$('exercises').files[0];if(!file)return;notice('Importing exercise drafts…');const result=await request('import-exercises',JSON.parse(await file.text()));await refresh();notice(result.warning||'Exercise drafts added. Release the updated catalogue to use them in the app.');$('exercises').value='';});
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
perform(()=>refresh());
